spring:
  application:
    name: @pom.artifactId@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: root
    url: jdbc:mysql://localhost:3306/cmscloud?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8