server:
  port: 8763

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.138:8848
      config:
        server-addr: 192.168.31.138:8848
        file-extension: yml
  profiles:
    active: dev


