server:
  port: 9411
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: @pom.artifactId@
management:
  metrics:
    web:
      server:
        auto-time-requests: false